apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: spark-master
  name: spark-np
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: port-1
      nodePort: 32507
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: port-2
      nodePort: 30897
      port: 7077
      protocol: TCP
      targetPort: 7077
    - name: port-3
      nodePort: 30981
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: port-4
      nodePort: 31953
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    io.kompose.service: spark-master
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}