apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-master
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/localnet: "true"
        io.kompose.service: spark-master
    spec:
      containers:
        - env:
            - name: AWS_BUCKET_NAME
              value: data-store
            - name: DEPLOY_ENV
              value: prod
            - name: JDBC_PWD
              value: tiger
            - name: JDBC_URL
              value: jdbc:mariadb://mariadb:3306/rnctech
            - name: JDBC_USER
              value: root
            - name: MINIO_ROOT_PASSWORD
              value: V7f1CwQqAcwo80March141966SSx5ohQ9GSrr12
            - name: MINIO_ROOT_USER
              value: ALANCHEN20211228S3KEY
            - name: S3_ACCESS_KEY_ID
              value: ALANCHEN20211228S3KEY
            - name: S3_SECRET_ACCESS_KEY
              value: V7f1CwQqAcwo80March141966SSx5ohQ9GSrr12
            - name: SPARK_MODE
              value: master
          image: rnctech/spark:latest
          name: rnc-master
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 7077
            - containerPort: 9000
            - containerPort: 9001
          resources: {}
          volumeMounts:
            - mountPath: /var/data
              name: sparkdata
      hostname: spark-master
      restartPolicy: Always
      volumes:
        - name: sparkdata
          persistentVolumeClaim:
            claimName: sparkdata
status: {}
